# Generated by Django 2.0.1 on 2018-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180308_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../static/assets/c_mor.png', upload_to=''),
        ),
    ]
